server:
  port: 9050

spring:
  datasource:
    username: yours username
    password: yours password
    url: yours url
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  rabbitmq:
    host: yours host
    port: 0000
    username: your name
    password: yours password
    virtual-host: yours virtual-host